name: счастье
favicon: null
layout_spectrum: 0.8205116111785173
typography_spectrum: 0.74257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d3380'
    - '#ffffff'
    - '#8b96bd'
    - '#80ffff'
    - '#0000ff'
  brandStrength: 1
  lightness: 0.6894174229819328
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
