name: счастье
favicon: null
layout_spectrum: 0.8377038463950157
typography_spectrum: 0.8317755521275103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E7E0C8'
    - '#1F1A17'
    - '#B2AB9E'
    - '#38748D'
    - '#595148'
  brandStrength: 0.0769275613129139
  lightness: 0.08842813037335873
  saturation: 0.31819947715848684
  rhythmicContrast: 0.017586908536031842
purpose: []
